name: Go Tests

on:
  push:
    branches:
      - '**' # Triggers on push to any branch
  pull_request:
    branches:
      - main # Triggers on pull requests targeting the main branch

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      # Set the working directory to /switch
      - name: Set Working Directory
        run: cd switch

      # Cache Go modules
      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Install Dependencies
      - name: Install Dependencies
        run: |
          cd switch
          go mod tidy

      # Run Tests
      - name: Run Tests
        run: |
          cd switch
          go test . -v
